project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "**Levy Economics Institute**: Online Appendix"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



