## Gender

### Gender

{{< include resources/y2021/f2021_sex_none.md >}}
:Distribution Balance {#tbl-bal2021_sex_none}

### Gender x Employed Status

{{< include resources/y2021/f2021_sex_employed.md >}}
:Distribution Balance {#tbl-bal2021_sex_employed}

### Gender x Young Child

{{< include resources/y2021/f2021_sex_ych.md >}}
:Distribution Balance {#tbl-bal2021_sex_ych}

### Gender x Couple

{{< include resources/y2021/f2021_sex_iscouple.md >}}
:Distribution Balance {#tbl-bal2021_sex_iscouple}

### Gender x Race

{{< include resources/y2021/f2021_sex_race.md >}}
:Distribution Balance {#tbl-bal2021_sex_race}

### Gender x Education

{{< include resources/y2021/f2021_sex_educ_tb.md >}}
:Distribution Balance {#tbl-bal2021_sex_educ_tb}

### Gender x Age Group

{{< include resources/y2021/f2021_sex_age_group.md >}}
:Distribution Balance {#tbl-bal2021_sex_age_group}

### Gender x # Children

{{< include resources/y2021/f2021_sex_ntchild.md >}}
:Distribution Balance {#tbl-bal2021_sex_ntchild}

### Gender x # Adults

{{< include resources/y2021/f2021_sex_ntadult.md >}}
:Distribution Balance {#tbl-bal2021_sex_ntadult}

### Gender x Family Income

{{< include resources/y2021/f2021_sex_faminc_q.md >}}
:Distribution Balance {#tbl-bal2021_sex_faminc_q}

## Employed Status

### Employed Status

{{< include resources/y2021/f2021_employed_none.md >}}
:Distribution Balance {#tbl-bal2021_employed_none}

### Employed Status x Gender

{{< include resources/y2021/f2021_employed_sex.md >}}
:Distribution Balance {#tbl-bal2021_employed_sex}

### Employed Status x Young Child

{{< include resources/y2021/f2021_employed_ych.md >}}
:Distribution Balance {#tbl-bal2021_employed_ych}

### Employed Status x Couple

{{< include resources/y2021/f2021_employed_iscouple.md >}}
:Distribution Balance {#tbl-bal2021_employed_iscouple}

### Employed Status x Race

{{< include resources/y2021/f2021_employed_race.md >}}
:Distribution Balance {#tbl-bal2021_employed_race}

### Employed Status x Education

{{< include resources/y2021/f2021_employed_educ_tb.md >}}
:Distribution Balance {#tbl-bal2021_employed_educ_tb}

### Employed Status x Age Group

{{< include resources/y2021/f2021_employed_age_group.md >}}
:Distribution Balance {#tbl-bal2021_employed_age_group}

### Employed Status x # Children

{{< include resources/y2021/f2021_employed_ntchild.md >}}
:Distribution Balance {#tbl-bal2021_employed_ntchild}

### Employed Status x # Adults

{{< include resources/y2021/f2021_employed_ntadult.md >}}
:Distribution Balance {#tbl-bal2021_employed_ntadult}

### Employed Status x Family Income

{{< include resources/y2021/f2021_employed_faminc_q.md >}}
:Distribution Balance {#tbl-bal2021_employed_faminc_q}

## Young Child

### Young Child

{{< include resources/y2021/f2021_ych_none.md >}}
:Distribution Balance {#tbl-bal2021_ych_none}

### Young Child x Gender

{{< include resources/y2021/f2021_ych_sex.md >}}
:Distribution Balance {#tbl-bal2021_ych_sex}

### Young Child x Employed Status

{{< include resources/y2021/f2021_ych_employed.md >}}
:Distribution Balance {#tbl-bal2021_ych_employed}

### Young Child x Couple

{{< include resources/y2021/f2021_ych_iscouple.md >}}
:Distribution Balance {#tbl-bal2021_ych_iscouple}

### Young Child x Race

{{< include resources/y2021/f2021_ych_race.md >}}
:Distribution Balance {#tbl-bal2021_ych_race}

### Young Child x Education

{{< include resources/y2021/f2021_ych_educ_tb.md >}}
:Distribution Balance {#tbl-bal2021_ych_educ_tb}

### Young Child x Age Group

{{< include resources/y2021/f2021_ych_age_group.md >}}
:Distribution Balance {#tbl-bal2021_ych_age_group}

### Young Child x # Children

{{< include resources/y2021/f2021_ych_ntchild.md >}}
:Distribution Balance {#tbl-bal2021_ych_ntchild}

### Young Child x # Adults

{{< include resources/y2021/f2021_ych_ntadult.md >}}
:Distribution Balance {#tbl-bal2021_ych_ntadult}

### Young Child x Family Income

{{< include resources/y2021/f2021_ych_faminc_q.md >}}
:Distribution Balance {#tbl-bal2021_ych_faminc_q}

## Couple

### Couple

{{< include resources/y2021/f2021_iscouple_none.md >}}
:Distribution Balance {#tbl-bal2021_iscouple_none}

### Couple x Gender

{{< include resources/y2021/f2021_iscouple_sex.md >}}
:Distribution Balance {#tbl-bal2021_iscouple_sex}

### Couple x Employed Status

{{< include resources/y2021/f2021_iscouple_employed.md >}}
:Distribution Balance {#tbl-bal2021_iscouple_employed}

### Couple x Young Child

{{< include resources/y2021/f2021_iscouple_ych.md >}}
:Distribution Balance {#tbl-bal2021_iscouple_ych}

### Couple x Race

{{< include resources/y2021/f2021_iscouple_race.md >}}
:Distribution Balance {#tbl-bal2021_iscouple_race}

### Couple x Education

{{< include resources/y2021/f2021_iscouple_educ_tb.md >}}
:Distribution Balance {#tbl-bal2021_iscouple_educ_tb}

### Couple x Age Group

{{< include resources/y2021/f2021_iscouple_age_group.md >}}
:Distribution Balance {#tbl-bal2021_iscouple_age_group}

### Couple x # Children

{{< include resources/y2021/f2021_iscouple_ntchild.md >}}
:Distribution Balance {#tbl-bal2021_iscouple_ntchild}

### Couple x # Adults

{{< include resources/y2021/f2021_iscouple_ntadult.md >}}
:Distribution Balance {#tbl-bal2021_iscouple_ntadult}

### Couple x Family Income

{{< include resources/y2021/f2021_iscouple_faminc_q.md >}}
:Distribution Balance {#tbl-bal2021_iscouple_faminc_q}

## Race

### Race

{{< include resources/y2021/f2021_race_none.md >}}
:Distribution Balance {#tbl-bal2021_race_none}

### Race x Gender

{{< include resources/y2021/f2021_race_sex.md >}}
:Distribution Balance {#tbl-bal2021_race_sex}

### Race x Employed Status

{{< include resources/y2021/f2021_race_employed.md >}}
:Distribution Balance {#tbl-bal2021_race_employed}

### Race x Young Child

{{< include resources/y2021/f2021_race_ych.md >}}
:Distribution Balance {#tbl-bal2021_race_ych}

### Race x Couple

{{< include resources/y2021/f2021_race_iscouple.md >}}
:Distribution Balance {#tbl-bal2021_race_iscouple}

### Race x Education

{{< include resources/y2021/f2021_race_educ_tb.md >}}
:Distribution Balance {#tbl-bal2021_race_educ_tb}

### Race x Age Group

{{< include resources/y2021/f2021_race_age_group.md >}}
:Distribution Balance {#tbl-bal2021_race_age_group}

### Race x # Children

{{< include resources/y2021/f2021_race_ntchild.md >}}
:Distribution Balance {#tbl-bal2021_race_ntchild}

### Race x # Adults

{{< include resources/y2021/f2021_race_ntadult.md >}}
:Distribution Balance {#tbl-bal2021_race_ntadult}

### Race x Family Income

{{< include resources/y2021/f2021_race_faminc_q.md >}}
:Distribution Balance {#tbl-bal2021_race_faminc_q}

## Education

### Education

{{< include resources/y2021/f2021_educ_tb_none.md >}}
:Distribution Balance {#tbl-bal2021_educ_tb_none}

### Education x Gender

{{< include resources/y2021/f2021_educ_tb_sex.md >}}
:Distribution Balance {#tbl-bal2021_educ_tb_sex}

### Education x Employed Status

{{< include resources/y2021/f2021_educ_tb_employed.md >}}
:Distribution Balance {#tbl-bal2021_educ_tb_employed}

### Education x Young Child

{{< include resources/y2021/f2021_educ_tb_ych.md >}}
:Distribution Balance {#tbl-bal2021_educ_tb_ych}

### Education x Couple

{{< include resources/y2021/f2021_educ_tb_iscouple.md >}}
:Distribution Balance {#tbl-bal2021_educ_tb_iscouple}

### Education x Race

{{< include resources/y2021/f2021_educ_tb_race.md >}}
:Distribution Balance {#tbl-bal2021_educ_tb_race}

### Education x Age Group

{{< include resources/y2021/f2021_educ_tb_age_group.md >}}
:Distribution Balance {#tbl-bal2021_educ_tb_age_group}

### Education x # Children

{{< include resources/y2021/f2021_educ_tb_ntchild.md >}}
:Distribution Balance {#tbl-bal2021_educ_tb_ntchild}

### Education x # Adults

{{< include resources/y2021/f2021_educ_tb_ntadult.md >}}
:Distribution Balance {#tbl-bal2021_educ_tb_ntadult}

### Education x Family Income

{{< include resources/y2021/f2021_educ_tb_faminc_q.md >}}
:Distribution Balance {#tbl-bal2021_educ_tb_faminc_q}

## Age Group

### Age Group

{{< include resources/y2021/f2021_age_group_none.md >}}
:Distribution Balance {#tbl-bal2021_age_group_none}

### Age Group x Gender

{{< include resources/y2021/f2021_age_group_sex.md >}}
:Distribution Balance {#tbl-bal2021_age_group_sex}

### Age Group x Employed Status

{{< include resources/y2021/f2021_age_group_employed.md >}}
:Distribution Balance {#tbl-bal2021_age_group_employed}

### Age Group x Young Child

{{< include resources/y2021/f2021_age_group_ych.md >}}
:Distribution Balance {#tbl-bal2021_age_group_ych}

### Age Group x Couple

{{< include resources/y2021/f2021_age_group_iscouple.md >}}
:Distribution Balance {#tbl-bal2021_age_group_iscouple}

### Age Group x Race

{{< include resources/y2021/f2021_age_group_race.md >}}
:Distribution Balance {#tbl-bal2021_age_group_race}

### Age Group x Education

{{< include resources/y2021/f2021_age_group_educ_tb.md >}}
:Distribution Balance {#tbl-bal2021_age_group_educ_tb}

### Age Group x # Children

{{< include resources/y2021/f2021_age_group_ntchild.md >}}
:Distribution Balance {#tbl-bal2021_age_group_ntchild}

### Age Group x # Adults

{{< include resources/y2021/f2021_age_group_ntadult.md >}}
:Distribution Balance {#tbl-bal2021_age_group_ntadult}

### Age Group x Family Income

{{< include resources/y2021/f2021_age_group_faminc_q.md >}}
:Distribution Balance {#tbl-bal2021_age_group_faminc_q}

## # Children

### # Children

{{< include resources/y2021/f2021_ntchild_none.md >}}
:Distribution Balance {#tbl-bal2021_ntchild_none}

### # Children x Gender

{{< include resources/y2021/f2021_ntchild_sex.md >}}
:Distribution Balance {#tbl-bal2021_ntchild_sex}

### # Children x Employed Status

{{< include resources/y2021/f2021_ntchild_employed.md >}}
:Distribution Balance {#tbl-bal2021_ntchild_employed}

### # Children x Young Child

{{< include resources/y2021/f2021_ntchild_ych.md >}}
:Distribution Balance {#tbl-bal2021_ntchild_ych}

### # Children x Couple

{{< include resources/y2021/f2021_ntchild_iscouple.md >}}
:Distribution Balance {#tbl-bal2021_ntchild_iscouple}

### # Children x Race

{{< include resources/y2021/f2021_ntchild_race.md >}}
:Distribution Balance {#tbl-bal2021_ntchild_race}

### # Children x Education

{{< include resources/y2021/f2021_ntchild_educ_tb.md >}}
:Distribution Balance {#tbl-bal2021_ntchild_educ_tb}

### # Children x Age Group

{{< include resources/y2021/f2021_ntchild_age_group.md >}}
:Distribution Balance {#tbl-bal2021_ntchild_age_group}

### # Children x # Adults

{{< include resources/y2021/f2021_ntchild_ntadult.md >}}
:Distribution Balance {#tbl-bal2021_ntchild_ntadult}

### # Children x Family Income

{{< include resources/y2021/f2021_ntchild_faminc_q.md >}}
:Distribution Balance {#tbl-bal2021_ntchild_faminc_q}

## # Adults

### # Adults

{{< include resources/y2021/f2021_ntadult_none.md >}}
:Distribution Balance {#tbl-bal2021_ntadult_none}

### # Adults x Gender

{{< include resources/y2021/f2021_ntadult_sex.md >}}
:Distribution Balance {#tbl-bal2021_ntadult_sex}

### # Adults x Employed Status

{{< include resources/y2021/f2021_ntadult_employed.md >}}
:Distribution Balance {#tbl-bal2021_ntadult_employed}

### # Adults x Young Child

{{< include resources/y2021/f2021_ntadult_ych.md >}}
:Distribution Balance {#tbl-bal2021_ntadult_ych}

### # Adults x Couple

{{< include resources/y2021/f2021_ntadult_iscouple.md >}}
:Distribution Balance {#tbl-bal2021_ntadult_iscouple}

### # Adults x Race

{{< include resources/y2021/f2021_ntadult_race.md >}}
:Distribution Balance {#tbl-bal2021_ntadult_race}

### # Adults x Education

{{< include resources/y2021/f2021_ntadult_educ_tb.md >}}
:Distribution Balance {#tbl-bal2021_ntadult_educ_tb}

### # Adults x Age Group

{{< include resources/y2021/f2021_ntadult_age_group.md >}}
:Distribution Balance {#tbl-bal2021_ntadult_age_group}

### # Adults x # Children

{{< include resources/y2021/f2021_ntadult_ntchild.md >}}
:Distribution Balance {#tbl-bal2021_ntadult_ntchild}

### # Adults x Family Income

{{< include resources/y2021/f2021_ntadult_faminc_q.md >}}
:Distribution Balance {#tbl-bal2021_ntadult_faminc_q}

## Family Income

### Family Income

{{< include resources/y2021/f2021_faminc_q_none.md >}}
:Distribution Balance {#tbl-bal2021_faminc_q_none}

### Family Income x Gender

{{< include resources/y2021/f2021_faminc_q_sex.md >}}
:Distribution Balance {#tbl-bal2021_faminc_q_sex}

### Family Income x Employed Status

{{< include resources/y2021/f2021_faminc_q_employed.md >}}
:Distribution Balance {#tbl-bal2021_faminc_q_employed}

### Family Income x Young Child

{{< include resources/y2021/f2021_faminc_q_ych.md >}}
:Distribution Balance {#tbl-bal2021_faminc_q_ych}

### Family Income x Couple

{{< include resources/y2021/f2021_faminc_q_iscouple.md >}}
:Distribution Balance {#tbl-bal2021_faminc_q_iscouple}

### Family Income x Race

{{< include resources/y2021/f2021_faminc_q_race.md >}}
:Distribution Balance {#tbl-bal2021_faminc_q_race}

### Family Income x Education

{{< include resources/y2021/f2021_faminc_q_educ_tb.md >}}
:Distribution Balance {#tbl-bal2021_faminc_q_educ_tb}

### Family Income x Age Group

{{< include resources/y2021/f2021_faminc_q_age_group.md >}}
:Distribution Balance {#tbl-bal2021_faminc_q_age_group}

### Family Income x # Children

{{< include resources/y2021/f2021_faminc_q_ntchild.md >}}
:Distribution Balance {#tbl-bal2021_faminc_q_ntchild}

### Family Income x # Adults

{{< include resources/y2021/f2021_faminc_q_ntadult.md >}}
:Distribution Balance {#tbl-bal2021_faminc_q_ntadult}

