## Gender

### Gender

{{< include resources/balance_sex_wday.md >}}
:Distribution Balance {#tbl-bsexwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_sex_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnsexwdaysm}

## Median 

{{< include resources/median_sex_wday_sm.md >}}
:Match Quality: Median {#tbl-mdsexwdaysm}

## SD 

{{< include resources/sd_sex_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdsexwdaysm}

::: 

### Race x Gender

{{< include resources/balance_race_sex_wday.md >}}
:Distribution Balance {#tbl-brace_sexwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_race_sex_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnrace_sexwdaysm}

## Median 

{{< include resources/median_race_sex_wday_sm.md >}}
:Match Quality: Median {#tbl-mdrace_sexwdaysm}

## SD 

{{< include resources/sd_race_sex_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdrace_sexwdaysm}

::: 

### Young Children x Gender

{{< include resources/balance_ychild_sex_wday.md >}}
:Distribution Balance {#tbl-bychild_sexwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_ychild_sex_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnychild_sexwdaysm}

## Median 

{{< include resources/median_ychild_sex_wday_sm.md >}}
:Match Quality: Median {#tbl-mdychild_sexwdaysm}

## SD 

{{< include resources/sd_ychild_sex_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdychild_sexwdaysm}

::: 

### Working Status x Gender

{{< include resources/balance_works_sex_wday.md >}}
:Distribution Balance {#tbl-bworks_sexwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_works_sex_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnworks_sexwdaysm}

## Median 

{{< include resources/median_works_sex_wday_sm.md >}}
:Match Quality: Median {#tbl-mdworks_sexwdaysm}

## SD 

{{< include resources/sd_works_sex_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdworks_sexwdaysm}

::: 

### No of Children x Gender

{{< include resources/balance_tchild_sex_wday.md >}}
:Distribution Balance {#tbl-btchild_sexwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tchild_sex_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntchild_sexwdaysm}

## Median 

{{< include resources/median_tchild_sex_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtchild_sexwdaysm}

## SD 

{{< include resources/sd_tchild_sex_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtchild_sexwdaysm}

::: 

### No of Adults x Gender

{{< include resources/balance_tadult_sex_wday.md >}}
:Distribution Balance {#tbl-btadult_sexwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tadult_sex_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntadult_sexwdaysm}

## Median 

{{< include resources/median_tadult_sex_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtadult_sexwdaysm}

## SD 

{{< include resources/sd_tadult_sex_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtadult_sexwdaysm}

::: 

### Age group x Gender

{{< include resources/balance_age_g_sex_wday.md >}}
:Distribution Balance {#tbl-bage_g_sexwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_age_g_sex_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnage_g_sexwdaysm}

## Median 

{{< include resources/median_age_g_sex_wday_sm.md >}}
:Match Quality: Median {#tbl-mdage_g_sexwdaysm}

## SD 

{{< include resources/sd_age_g_sex_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdage_g_sexwdaysm}

::: 

### Single/Couple x Gender

{{< include resources/balance_cpl_sex_wday.md >}}
:Distribution Balance {#tbl-bcpl_sexwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_cpl_sex_wday_sm.md >}}
:Match Quality: Mean {#tbl-mncpl_sexwdaysm}

## Median 

{{< include resources/median_cpl_sex_wday_sm.md >}}
:Match Quality: Median {#tbl-mdcpl_sexwdaysm}

## SD 

{{< include resources/sd_cpl_sex_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdcpl_sexwdaysm}

::: 

### Education Level x Gender

{{< include resources/balance_educ_g_sex_wday.md >}}
:Distribution Balance {#tbl-beduc_g_sexwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_educ_g_sex_wday_sm.md >}}
:Match Quality: Mean {#tbl-mneduc_g_sexwdaysm}

## Median 

{{< include resources/median_educ_g_sex_wday_sm.md >}}
:Match Quality: Median {#tbl-mdeduc_g_sexwdaysm}

## SD 

{{< include resources/sd_educ_g_sex_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdeduc_g_sexwdaysm}

::: 

### Income Quantile x Gender

{{< include resources/balance_q5_sex_wday.md >}}
:Distribution Balance {#tbl-bq5_sexwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_q5_sex_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnq5_sexwdaysm}

## Median 

{{< include resources/median_q5_sex_wday_sm.md >}}
:Match Quality: Median {#tbl-mdq5_sexwdaysm}

## SD 

{{< include resources/sd_q5_sex_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdq5_sexwdaysm}

::: 

### Home Ownership x Gender

{{< include resources/balance_hhown_sex_wday.md >}}
:Distribution Balance {#tbl-bhhown_sexwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_hhown_sex_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnhhown_sexwdaysm}

## Median 

{{< include resources/median_hhown_sex_wday_sm.md >}}
:Match Quality: Median {#tbl-mdhhown_sexwdaysm}

## SD 

{{< include resources/sd_hhown_sex_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdhhown_sexwdaysm}

::: 

## Race

### Race

{{< include resources/balance_race_wday.md >}}
:Distribution Balance {#tbl-bracewdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_race_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnracewdaysm}

## Median 

{{< include resources/median_race_wday_sm.md >}}
:Match Quality: Median {#tbl-mdracewdaysm}

## SD 

{{< include resources/sd_race_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdracewdaysm}

::: 

### Race x Gender

{{< include resources/balance_race_sex_wday.md >}}
:Distribution Balance {#tbl-brace_sexwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_race_sex_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnrace_sexwdaysm}

## Median 

{{< include resources/median_race_sex_wday_sm.md >}}
:Match Quality: Median {#tbl-mdrace_sexwdaysm}

## SD 

{{< include resources/sd_race_sex_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdrace_sexwdaysm}

::: 

### Race x Young Children

{{< include resources/balance_race_ychild_wday.md >}}
:Distribution Balance {#tbl-brace_ychildwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_race_ychild_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnrace_ychildwdaysm}

## Median 

{{< include resources/median_race_ychild_wday_sm.md >}}
:Match Quality: Median {#tbl-mdrace_ychildwdaysm}

## SD 

{{< include resources/sd_race_ychild_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdrace_ychildwdaysm}

::: 

### Race x Working Status

{{< include resources/balance_race_works_wday.md >}}
:Distribution Balance {#tbl-brace_workswdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_race_works_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnrace_workswdaysm}

## Median 

{{< include resources/median_race_works_wday_sm.md >}}
:Match Quality: Median {#tbl-mdrace_workswdaysm}

## SD 

{{< include resources/sd_race_works_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdrace_workswdaysm}

::: 

### Race x No of Children

{{< include resources/balance_race_tchild_wday.md >}}
:Distribution Balance {#tbl-brace_tchildwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_race_tchild_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnrace_tchildwdaysm}

## Median 

{{< include resources/median_race_tchild_wday_sm.md >}}
:Match Quality: Median {#tbl-mdrace_tchildwdaysm}

## SD 

{{< include resources/sd_race_tchild_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdrace_tchildwdaysm}

::: 

### Race x No of Adults

{{< include resources/balance_race_tadult_wday.md >}}
:Distribution Balance {#tbl-brace_tadultwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_race_tadult_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnrace_tadultwdaysm}

## Median 

{{< include resources/median_race_tadult_wday_sm.md >}}
:Match Quality: Median {#tbl-mdrace_tadultwdaysm}

## SD 

{{< include resources/sd_race_tadult_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdrace_tadultwdaysm}

::: 

### Race x Age group

{{< include resources/balance_race_age_g_wday.md >}}
:Distribution Balance {#tbl-brace_age_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_race_age_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnrace_age_gwdaysm}

## Median 

{{< include resources/median_race_age_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdrace_age_gwdaysm}

## SD 

{{< include resources/sd_race_age_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdrace_age_gwdaysm}

::: 

### Race x Single/Couple

{{< include resources/balance_race_cpl_wday.md >}}
:Distribution Balance {#tbl-brace_cplwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_race_cpl_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnrace_cplwdaysm}

## Median 

{{< include resources/median_race_cpl_wday_sm.md >}}
:Match Quality: Median {#tbl-mdrace_cplwdaysm}

## SD 

{{< include resources/sd_race_cpl_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdrace_cplwdaysm}

::: 

### Race x Education Level

{{< include resources/balance_race_educ_g_wday.md >}}
:Distribution Balance {#tbl-brace_educ_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_race_educ_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnrace_educ_gwdaysm}

## Median 

{{< include resources/median_race_educ_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdrace_educ_gwdaysm}

## SD 

{{< include resources/sd_race_educ_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdrace_educ_gwdaysm}

::: 

### Race x Income Quantile

{{< include resources/balance_race_q5_wday.md >}}
:Distribution Balance {#tbl-brace_q5wdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_race_q5_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnrace_q5wdaysm}

## Median 

{{< include resources/median_race_q5_wday_sm.md >}}
:Match Quality: Median {#tbl-mdrace_q5wdaysm}

## SD 

{{< include resources/sd_race_q5_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdrace_q5wdaysm}

::: 

### Race x Home Ownership

{{< include resources/balance_race_hhown_wday.md >}}
:Distribution Balance {#tbl-brace_hhownwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_race_hhown_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnrace_hhownwdaysm}

## Median 

{{< include resources/median_race_hhown_wday_sm.md >}}
:Match Quality: Median {#tbl-mdrace_hhownwdaysm}

## SD 

{{< include resources/sd_race_hhown_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdrace_hhownwdaysm}

::: 

## Young Children

### Young Children

{{< include resources/balance_ychild_wday.md >}}
:Distribution Balance {#tbl-bychildwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_ychild_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnychildwdaysm}

## Median 

{{< include resources/median_ychild_wday_sm.md >}}
:Match Quality: Median {#tbl-mdychildwdaysm}

## SD 

{{< include resources/sd_ychild_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdychildwdaysm}

::: 

### Young Children x Gender

{{< include resources/balance_ychild_sex_wday.md >}}
:Distribution Balance {#tbl-bychild_sexwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_ychild_sex_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnychild_sexwdaysm}

## Median 

{{< include resources/median_ychild_sex_wday_sm.md >}}
:Match Quality: Median {#tbl-mdychild_sexwdaysm}

## SD 

{{< include resources/sd_ychild_sex_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdychild_sexwdaysm}

::: 

### Race x Young Children

{{< include resources/balance_race_ychild_wday.md >}}
:Distribution Balance {#tbl-brace_ychildwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_race_ychild_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnrace_ychildwdaysm}

## Median 

{{< include resources/median_race_ychild_wday_sm.md >}}
:Match Quality: Median {#tbl-mdrace_ychildwdaysm}

## SD 

{{< include resources/sd_race_ychild_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdrace_ychildwdaysm}

::: 

### Young Children x Working Status

{{< include resources/balance_ychild_works_wday.md >}}
:Distribution Balance {#tbl-bychild_workswdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_ychild_works_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnychild_workswdaysm}

## Median 

{{< include resources/median_ychild_works_wday_sm.md >}}
:Match Quality: Median {#tbl-mdychild_workswdaysm}

## SD 

{{< include resources/sd_ychild_works_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdychild_workswdaysm}

::: 

### Young Children x No of Children

{{< include resources/balance_ychild_tchild_wday.md >}}
:Distribution Balance {#tbl-bychild_tchildwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_ychild_tchild_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnychild_tchildwdaysm}

## Median 

{{< include resources/median_ychild_tchild_wday_sm.md >}}
:Match Quality: Median {#tbl-mdychild_tchildwdaysm}

## SD 

{{< include resources/sd_ychild_tchild_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdychild_tchildwdaysm}

::: 

### Young Children x No of Adults

{{< include resources/balance_ychild_tadult_wday.md >}}
:Distribution Balance {#tbl-bychild_tadultwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_ychild_tadult_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnychild_tadultwdaysm}

## Median 

{{< include resources/median_ychild_tadult_wday_sm.md >}}
:Match Quality: Median {#tbl-mdychild_tadultwdaysm}

## SD 

{{< include resources/sd_ychild_tadult_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdychild_tadultwdaysm}

::: 

### Young Children x Age group

{{< include resources/balance_ychild_age_g_wday.md >}}
:Distribution Balance {#tbl-bychild_age_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_ychild_age_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnychild_age_gwdaysm}

## Median 

{{< include resources/median_ychild_age_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdychild_age_gwdaysm}

## SD 

{{< include resources/sd_ychild_age_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdychild_age_gwdaysm}

::: 

### Young Children x Single/Couple

{{< include resources/balance_ychild_cpl_wday.md >}}
:Distribution Balance {#tbl-bychild_cplwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_ychild_cpl_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnychild_cplwdaysm}

## Median 

{{< include resources/median_ychild_cpl_wday_sm.md >}}
:Match Quality: Median {#tbl-mdychild_cplwdaysm}

## SD 

{{< include resources/sd_ychild_cpl_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdychild_cplwdaysm}

::: 

### Young Children x Education Level

{{< include resources/balance_ychild_educ_g_wday.md >}}
:Distribution Balance {#tbl-bychild_educ_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_ychild_educ_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnychild_educ_gwdaysm}

## Median 

{{< include resources/median_ychild_educ_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdychild_educ_gwdaysm}

## SD 

{{< include resources/sd_ychild_educ_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdychild_educ_gwdaysm}

::: 

### Young Children x Income Quantile

{{< include resources/balance_ychild_q5_wday.md >}}
:Distribution Balance {#tbl-bychild_q5wdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_ychild_q5_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnychild_q5wdaysm}

## Median 

{{< include resources/median_ychild_q5_wday_sm.md >}}
:Match Quality: Median {#tbl-mdychild_q5wdaysm}

## SD 

{{< include resources/sd_ychild_q5_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdychild_q5wdaysm}

::: 

### Young Children x Home Ownership

{{< include resources/balance_ychild_hhown_wday.md >}}
:Distribution Balance {#tbl-bychild_hhownwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_ychild_hhown_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnychild_hhownwdaysm}

## Median 

{{< include resources/median_ychild_hhown_wday_sm.md >}}
:Match Quality: Median {#tbl-mdychild_hhownwdaysm}

## SD 

{{< include resources/sd_ychild_hhown_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdychild_hhownwdaysm}

::: 

## Working Status

### Working Status

{{< include resources/balance_works_wday.md >}}
:Distribution Balance {#tbl-bworkswdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_works_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnworkswdaysm}

## Median 

{{< include resources/median_works_wday_sm.md >}}
:Match Quality: Median {#tbl-mdworkswdaysm}

## SD 

{{< include resources/sd_works_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdworkswdaysm}

::: 

### Working Status x Gender

{{< include resources/balance_works_sex_wday.md >}}
:Distribution Balance {#tbl-bworks_sexwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_works_sex_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnworks_sexwdaysm}

## Median 

{{< include resources/median_works_sex_wday_sm.md >}}
:Match Quality: Median {#tbl-mdworks_sexwdaysm}

## SD 

{{< include resources/sd_works_sex_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdworks_sexwdaysm}

::: 

### Race x Working Status

{{< include resources/balance_race_works_wday.md >}}
:Distribution Balance {#tbl-brace_workswdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_race_works_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnrace_workswdaysm}

## Median 

{{< include resources/median_race_works_wday_sm.md >}}
:Match Quality: Median {#tbl-mdrace_workswdaysm}

## SD 

{{< include resources/sd_race_works_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdrace_workswdaysm}

::: 

### Young Children x Working Status

{{< include resources/balance_ychild_works_wday.md >}}
:Distribution Balance {#tbl-bychild_workswdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_ychild_works_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnychild_workswdaysm}

## Median 

{{< include resources/median_ychild_works_wday_sm.md >}}
:Match Quality: Median {#tbl-mdychild_workswdaysm}

## SD 

{{< include resources/sd_ychild_works_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdychild_workswdaysm}

::: 

### Working Status x No of Children

{{< include resources/balance_works_tchild_wday.md >}}
:Distribution Balance {#tbl-bworks_tchildwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_works_tchild_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnworks_tchildwdaysm}

## Median 

{{< include resources/median_works_tchild_wday_sm.md >}}
:Match Quality: Median {#tbl-mdworks_tchildwdaysm}

## SD 

{{< include resources/sd_works_tchild_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdworks_tchildwdaysm}

::: 

### Working Status x No of Adults

{{< include resources/balance_works_tadult_wday.md >}}
:Distribution Balance {#tbl-bworks_tadultwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_works_tadult_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnworks_tadultwdaysm}

## Median 

{{< include resources/median_works_tadult_wday_sm.md >}}
:Match Quality: Median {#tbl-mdworks_tadultwdaysm}

## SD 

{{< include resources/sd_works_tadult_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdworks_tadultwdaysm}

::: 

### Working Status x Age group

{{< include resources/balance_works_age_g_wday.md >}}
:Distribution Balance {#tbl-bworks_age_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_works_age_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnworks_age_gwdaysm}

## Median 

{{< include resources/median_works_age_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdworks_age_gwdaysm}

## SD 

{{< include resources/sd_works_age_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdworks_age_gwdaysm}

::: 

### Working Status x Single/Couple

{{< include resources/balance_works_cpl_wday.md >}}
:Distribution Balance {#tbl-bworks_cplwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_works_cpl_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnworks_cplwdaysm}

## Median 

{{< include resources/median_works_cpl_wday_sm.md >}}
:Match Quality: Median {#tbl-mdworks_cplwdaysm}

## SD 

{{< include resources/sd_works_cpl_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdworks_cplwdaysm}

::: 

### Working Status x Education Level

{{< include resources/balance_works_educ_g_wday.md >}}
:Distribution Balance {#tbl-bworks_educ_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_works_educ_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnworks_educ_gwdaysm}

## Median 

{{< include resources/median_works_educ_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdworks_educ_gwdaysm}

## SD 

{{< include resources/sd_works_educ_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdworks_educ_gwdaysm}

::: 

### Working Status x Income Quantile

{{< include resources/balance_works_q5_wday.md >}}
:Distribution Balance {#tbl-bworks_q5wdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_works_q5_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnworks_q5wdaysm}

## Median 

{{< include resources/median_works_q5_wday_sm.md >}}
:Match Quality: Median {#tbl-mdworks_q5wdaysm}

## SD 

{{< include resources/sd_works_q5_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdworks_q5wdaysm}

::: 

### Working Status x Home Ownership

{{< include resources/balance_works_hhown_wday.md >}}
:Distribution Balance {#tbl-bworks_hhownwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_works_hhown_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnworks_hhownwdaysm}

## Median 

{{< include resources/median_works_hhown_wday_sm.md >}}
:Match Quality: Median {#tbl-mdworks_hhownwdaysm}

## SD 

{{< include resources/sd_works_hhown_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdworks_hhownwdaysm}

::: 

## No of Children

### No of Children

{{< include resources/balance_tchild_wday.md >}}
:Distribution Balance {#tbl-btchildwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tchild_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntchildwdaysm}

## Median 

{{< include resources/median_tchild_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtchildwdaysm}

## SD 

{{< include resources/sd_tchild_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtchildwdaysm}

::: 

### No of Children x Gender

{{< include resources/balance_tchild_sex_wday.md >}}
:Distribution Balance {#tbl-btchild_sexwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tchild_sex_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntchild_sexwdaysm}

## Median 

{{< include resources/median_tchild_sex_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtchild_sexwdaysm}

## SD 

{{< include resources/sd_tchild_sex_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtchild_sexwdaysm}

::: 

### Race x No of Children

{{< include resources/balance_race_tchild_wday.md >}}
:Distribution Balance {#tbl-brace_tchildwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_race_tchild_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnrace_tchildwdaysm}

## Median 

{{< include resources/median_race_tchild_wday_sm.md >}}
:Match Quality: Median {#tbl-mdrace_tchildwdaysm}

## SD 

{{< include resources/sd_race_tchild_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdrace_tchildwdaysm}

::: 

### Young Children x No of Children

{{< include resources/balance_ychild_tchild_wday.md >}}
:Distribution Balance {#tbl-bychild_tchildwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_ychild_tchild_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnychild_tchildwdaysm}

## Median 

{{< include resources/median_ychild_tchild_wday_sm.md >}}
:Match Quality: Median {#tbl-mdychild_tchildwdaysm}

## SD 

{{< include resources/sd_ychild_tchild_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdychild_tchildwdaysm}

::: 

### Working Status x No of Children

{{< include resources/balance_works_tchild_wday.md >}}
:Distribution Balance {#tbl-bworks_tchildwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_works_tchild_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnworks_tchildwdaysm}

## Median 

{{< include resources/median_works_tchild_wday_sm.md >}}
:Match Quality: Median {#tbl-mdworks_tchildwdaysm}

## SD 

{{< include resources/sd_works_tchild_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdworks_tchildwdaysm}

::: 

### No of Children x No of Adults

{{< include resources/balance_tchild_tadult_wday.md >}}
:Distribution Balance {#tbl-btchild_tadultwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tchild_tadult_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntchild_tadultwdaysm}

## Median 

{{< include resources/median_tchild_tadult_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtchild_tadultwdaysm}

## SD 

{{< include resources/sd_tchild_tadult_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtchild_tadultwdaysm}

::: 

### No of Children x Age group

{{< include resources/balance_tchild_age_g_wday.md >}}
:Distribution Balance {#tbl-btchild_age_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tchild_age_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntchild_age_gwdaysm}

## Median 

{{< include resources/median_tchild_age_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtchild_age_gwdaysm}

## SD 

{{< include resources/sd_tchild_age_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtchild_age_gwdaysm}

::: 

### No of Children x Single/Couple

{{< include resources/balance_tchild_cpl_wday.md >}}
:Distribution Balance {#tbl-btchild_cplwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tchild_cpl_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntchild_cplwdaysm}

## Median 

{{< include resources/median_tchild_cpl_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtchild_cplwdaysm}

## SD 

{{< include resources/sd_tchild_cpl_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtchild_cplwdaysm}

::: 

### No of Children x Education Level

{{< include resources/balance_tchild_educ_g_wday.md >}}
:Distribution Balance {#tbl-btchild_educ_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tchild_educ_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntchild_educ_gwdaysm}

## Median 

{{< include resources/median_tchild_educ_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtchild_educ_gwdaysm}

## SD 

{{< include resources/sd_tchild_educ_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtchild_educ_gwdaysm}

::: 

### No of Children x Income Quantile

{{< include resources/balance_tchild_q5_wday.md >}}
:Distribution Balance {#tbl-btchild_q5wdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tchild_q5_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntchild_q5wdaysm}

## Median 

{{< include resources/median_tchild_q5_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtchild_q5wdaysm}

## SD 

{{< include resources/sd_tchild_q5_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtchild_q5wdaysm}

::: 

### No of Children x Home Ownership

{{< include resources/balance_tchild_hhown_wday.md >}}
:Distribution Balance {#tbl-btchild_hhownwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tchild_hhown_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntchild_hhownwdaysm}

## Median 

{{< include resources/median_tchild_hhown_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtchild_hhownwdaysm}

## SD 

{{< include resources/sd_tchild_hhown_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtchild_hhownwdaysm}

::: 

## No of Adults

### No of Adults

{{< include resources/balance_tadult_wday.md >}}
:Distribution Balance {#tbl-btadultwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tadult_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntadultwdaysm}

## Median 

{{< include resources/median_tadult_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtadultwdaysm}

## SD 

{{< include resources/sd_tadult_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtadultwdaysm}

::: 

### No of Adults x Gender

{{< include resources/balance_tadult_sex_wday.md >}}
:Distribution Balance {#tbl-btadult_sexwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tadult_sex_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntadult_sexwdaysm}

## Median 

{{< include resources/median_tadult_sex_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtadult_sexwdaysm}

## SD 

{{< include resources/sd_tadult_sex_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtadult_sexwdaysm}

::: 

### Race x No of Adults

{{< include resources/balance_race_tadult_wday.md >}}
:Distribution Balance {#tbl-brace_tadultwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_race_tadult_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnrace_tadultwdaysm}

## Median 

{{< include resources/median_race_tadult_wday_sm.md >}}
:Match Quality: Median {#tbl-mdrace_tadultwdaysm}

## SD 

{{< include resources/sd_race_tadult_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdrace_tadultwdaysm}

::: 

### Young Children x No of Adults

{{< include resources/balance_ychild_tadult_wday.md >}}
:Distribution Balance {#tbl-bychild_tadultwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_ychild_tadult_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnychild_tadultwdaysm}

## Median 

{{< include resources/median_ychild_tadult_wday_sm.md >}}
:Match Quality: Median {#tbl-mdychild_tadultwdaysm}

## SD 

{{< include resources/sd_ychild_tadult_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdychild_tadultwdaysm}

::: 

### Working Status x No of Adults

{{< include resources/balance_works_tadult_wday.md >}}
:Distribution Balance {#tbl-bworks_tadultwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_works_tadult_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnworks_tadultwdaysm}

## Median 

{{< include resources/median_works_tadult_wday_sm.md >}}
:Match Quality: Median {#tbl-mdworks_tadultwdaysm}

## SD 

{{< include resources/sd_works_tadult_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdworks_tadultwdaysm}

::: 

### No of Children x No of Adults

{{< include resources/balance_tchild_tadult_wday.md >}}
:Distribution Balance {#tbl-btchild_tadultwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tchild_tadult_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntchild_tadultwdaysm}

## Median 

{{< include resources/median_tchild_tadult_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtchild_tadultwdaysm}

## SD 

{{< include resources/sd_tchild_tadult_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtchild_tadultwdaysm}

::: 

### No of Adults x Age group

{{< include resources/balance_tadult_age_g_wday.md >}}
:Distribution Balance {#tbl-btadult_age_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tadult_age_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntadult_age_gwdaysm}

## Median 

{{< include resources/median_tadult_age_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtadult_age_gwdaysm}

## SD 

{{< include resources/sd_tadult_age_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtadult_age_gwdaysm}

::: 

### No of Adults x Single/Couple

{{< include resources/balance_tadult_cpl_wday.md >}}
:Distribution Balance {#tbl-btadult_cplwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tadult_cpl_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntadult_cplwdaysm}

## Median 

{{< include resources/median_tadult_cpl_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtadult_cplwdaysm}

## SD 

{{< include resources/sd_tadult_cpl_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtadult_cplwdaysm}

::: 

### No of Adults x Education Level

{{< include resources/balance_tadult_educ_g_wday.md >}}
:Distribution Balance {#tbl-btadult_educ_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tadult_educ_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntadult_educ_gwdaysm}

## Median 

{{< include resources/median_tadult_educ_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtadult_educ_gwdaysm}

## SD 

{{< include resources/sd_tadult_educ_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtadult_educ_gwdaysm}

::: 

### No of Adults x Income Quantile

{{< include resources/balance_tadult_q5_wday.md >}}
:Distribution Balance {#tbl-btadult_q5wdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tadult_q5_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntadult_q5wdaysm}

## Median 

{{< include resources/median_tadult_q5_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtadult_q5wdaysm}

## SD 

{{< include resources/sd_tadult_q5_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtadult_q5wdaysm}

::: 

### No of Adults x Home Ownership

{{< include resources/balance_tadult_hhown_wday.md >}}
:Distribution Balance {#tbl-btadult_hhownwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tadult_hhown_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntadult_hhownwdaysm}

## Median 

{{< include resources/median_tadult_hhown_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtadult_hhownwdaysm}

## SD 

{{< include resources/sd_tadult_hhown_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtadult_hhownwdaysm}

::: 

## Age group

### Age group

{{< include resources/balance_age_g_wday.md >}}
:Distribution Balance {#tbl-bage_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_age_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnage_gwdaysm}

## Median 

{{< include resources/median_age_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdage_gwdaysm}

## SD 

{{< include resources/sd_age_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdage_gwdaysm}

::: 

### Age group x Gender

{{< include resources/balance_age_g_sex_wday.md >}}
:Distribution Balance {#tbl-bage_g_sexwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_age_g_sex_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnage_g_sexwdaysm}

## Median 

{{< include resources/median_age_g_sex_wday_sm.md >}}
:Match Quality: Median {#tbl-mdage_g_sexwdaysm}

## SD 

{{< include resources/sd_age_g_sex_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdage_g_sexwdaysm}

::: 

### Race x Age group

{{< include resources/balance_race_age_g_wday.md >}}
:Distribution Balance {#tbl-brace_age_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_race_age_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnrace_age_gwdaysm}

## Median 

{{< include resources/median_race_age_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdrace_age_gwdaysm}

## SD 

{{< include resources/sd_race_age_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdrace_age_gwdaysm}

::: 

### Young Children x Age group

{{< include resources/balance_ychild_age_g_wday.md >}}
:Distribution Balance {#tbl-bychild_age_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_ychild_age_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnychild_age_gwdaysm}

## Median 

{{< include resources/median_ychild_age_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdychild_age_gwdaysm}

## SD 

{{< include resources/sd_ychild_age_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdychild_age_gwdaysm}

::: 

### Working Status x Age group

{{< include resources/balance_works_age_g_wday.md >}}
:Distribution Balance {#tbl-bworks_age_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_works_age_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnworks_age_gwdaysm}

## Median 

{{< include resources/median_works_age_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdworks_age_gwdaysm}

## SD 

{{< include resources/sd_works_age_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdworks_age_gwdaysm}

::: 

### No of Children x Age group

{{< include resources/balance_tchild_age_g_wday.md >}}
:Distribution Balance {#tbl-btchild_age_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tchild_age_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntchild_age_gwdaysm}

## Median 

{{< include resources/median_tchild_age_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtchild_age_gwdaysm}

## SD 

{{< include resources/sd_tchild_age_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtchild_age_gwdaysm}

::: 

### No of Adults x Age group

{{< include resources/balance_tadult_age_g_wday.md >}}
:Distribution Balance {#tbl-btadult_age_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tadult_age_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntadult_age_gwdaysm}

## Median 

{{< include resources/median_tadult_age_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtadult_age_gwdaysm}

## SD 

{{< include resources/sd_tadult_age_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtadult_age_gwdaysm}

::: 

### Age group x Single/Couple

{{< include resources/balance_age_g_cpl_wday.md >}}
:Distribution Balance {#tbl-bage_g_cplwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_age_g_cpl_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnage_g_cplwdaysm}

## Median 

{{< include resources/median_age_g_cpl_wday_sm.md >}}
:Match Quality: Median {#tbl-mdage_g_cplwdaysm}

## SD 

{{< include resources/sd_age_g_cpl_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdage_g_cplwdaysm}

::: 

### Age group x Education Level

{{< include resources/balance_age_g_educ_g_wday.md >}}
:Distribution Balance {#tbl-bage_g_educ_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_age_g_educ_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnage_g_educ_gwdaysm}

## Median 

{{< include resources/median_age_g_educ_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdage_g_educ_gwdaysm}

## SD 

{{< include resources/sd_age_g_educ_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdage_g_educ_gwdaysm}

::: 

### Age group x Income Quantile

{{< include resources/balance_age_g_q5_wday.md >}}
:Distribution Balance {#tbl-bage_g_q5wdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_age_g_q5_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnage_g_q5wdaysm}

## Median 

{{< include resources/median_age_g_q5_wday_sm.md >}}
:Match Quality: Median {#tbl-mdage_g_q5wdaysm}

## SD 

{{< include resources/sd_age_g_q5_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdage_g_q5wdaysm}

::: 

### Age group x Home Ownership

{{< include resources/balance_age_g_hhown_wday.md >}}
:Distribution Balance {#tbl-bage_g_hhownwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_age_g_hhown_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnage_g_hhownwdaysm}

## Median 

{{< include resources/median_age_g_hhown_wday_sm.md >}}
:Match Quality: Median {#tbl-mdage_g_hhownwdaysm}

## SD 

{{< include resources/sd_age_g_hhown_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdage_g_hhownwdaysm}

::: 

## Single/Couple

### Single/Couple

{{< include resources/balance_cpl_wday.md >}}
:Distribution Balance {#tbl-bcplwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_cpl_wday_sm.md >}}
:Match Quality: Mean {#tbl-mncplwdaysm}

## Median 

{{< include resources/median_cpl_wday_sm.md >}}
:Match Quality: Median {#tbl-mdcplwdaysm}

## SD 

{{< include resources/sd_cpl_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdcplwdaysm}

::: 

### Single/Couple x Gender

{{< include resources/balance_cpl_sex_wday.md >}}
:Distribution Balance {#tbl-bcpl_sexwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_cpl_sex_wday_sm.md >}}
:Match Quality: Mean {#tbl-mncpl_sexwdaysm}

## Median 

{{< include resources/median_cpl_sex_wday_sm.md >}}
:Match Quality: Median {#tbl-mdcpl_sexwdaysm}

## SD 

{{< include resources/sd_cpl_sex_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdcpl_sexwdaysm}

::: 

### Race x Single/Couple

{{< include resources/balance_race_cpl_wday.md >}}
:Distribution Balance {#tbl-brace_cplwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_race_cpl_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnrace_cplwdaysm}

## Median 

{{< include resources/median_race_cpl_wday_sm.md >}}
:Match Quality: Median {#tbl-mdrace_cplwdaysm}

## SD 

{{< include resources/sd_race_cpl_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdrace_cplwdaysm}

::: 

### Young Children x Single/Couple

{{< include resources/balance_ychild_cpl_wday.md >}}
:Distribution Balance {#tbl-bychild_cplwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_ychild_cpl_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnychild_cplwdaysm}

## Median 

{{< include resources/median_ychild_cpl_wday_sm.md >}}
:Match Quality: Median {#tbl-mdychild_cplwdaysm}

## SD 

{{< include resources/sd_ychild_cpl_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdychild_cplwdaysm}

::: 

### Working Status x Single/Couple

{{< include resources/balance_works_cpl_wday.md >}}
:Distribution Balance {#tbl-bworks_cplwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_works_cpl_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnworks_cplwdaysm}

## Median 

{{< include resources/median_works_cpl_wday_sm.md >}}
:Match Quality: Median {#tbl-mdworks_cplwdaysm}

## SD 

{{< include resources/sd_works_cpl_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdworks_cplwdaysm}

::: 

### No of Children x Single/Couple

{{< include resources/balance_tchild_cpl_wday.md >}}
:Distribution Balance {#tbl-btchild_cplwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tchild_cpl_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntchild_cplwdaysm}

## Median 

{{< include resources/median_tchild_cpl_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtchild_cplwdaysm}

## SD 

{{< include resources/sd_tchild_cpl_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtchild_cplwdaysm}

::: 

### No of Adults x Single/Couple

{{< include resources/balance_tadult_cpl_wday.md >}}
:Distribution Balance {#tbl-btadult_cplwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tadult_cpl_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntadult_cplwdaysm}

## Median 

{{< include resources/median_tadult_cpl_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtadult_cplwdaysm}

## SD 

{{< include resources/sd_tadult_cpl_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtadult_cplwdaysm}

::: 

### Age group x Single/Couple

{{< include resources/balance_age_g_cpl_wday.md >}}
:Distribution Balance {#tbl-bage_g_cplwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_age_g_cpl_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnage_g_cplwdaysm}

## Median 

{{< include resources/median_age_g_cpl_wday_sm.md >}}
:Match Quality: Median {#tbl-mdage_g_cplwdaysm}

## SD 

{{< include resources/sd_age_g_cpl_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdage_g_cplwdaysm}

::: 

### Single/Couple x Education Level

{{< include resources/balance_cpl_educ_g_wday.md >}}
:Distribution Balance {#tbl-bcpl_educ_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_cpl_educ_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mncpl_educ_gwdaysm}

## Median 

{{< include resources/median_cpl_educ_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdcpl_educ_gwdaysm}

## SD 

{{< include resources/sd_cpl_educ_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdcpl_educ_gwdaysm}

::: 

### Single/Couple x Income Quantile

{{< include resources/balance_cpl_q5_wday.md >}}
:Distribution Balance {#tbl-bcpl_q5wdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_cpl_q5_wday_sm.md >}}
:Match Quality: Mean {#tbl-mncpl_q5wdaysm}

## Median 

{{< include resources/median_cpl_q5_wday_sm.md >}}
:Match Quality: Median {#tbl-mdcpl_q5wdaysm}

## SD 

{{< include resources/sd_cpl_q5_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdcpl_q5wdaysm}

::: 

### Single/Couple x Home Ownership

{{< include resources/balance_cpl_hhown_wday.md >}}
:Distribution Balance {#tbl-bcpl_hhownwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_cpl_hhown_wday_sm.md >}}
:Match Quality: Mean {#tbl-mncpl_hhownwdaysm}

## Median 

{{< include resources/median_cpl_hhown_wday_sm.md >}}
:Match Quality: Median {#tbl-mdcpl_hhownwdaysm}

## SD 

{{< include resources/sd_cpl_hhown_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdcpl_hhownwdaysm}

::: 

## Education Level

### Education Level

{{< include resources/balance_educ_g_wday.md >}}
:Distribution Balance {#tbl-beduc_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_educ_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mneduc_gwdaysm}

## Median 

{{< include resources/median_educ_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdeduc_gwdaysm}

## SD 

{{< include resources/sd_educ_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdeduc_gwdaysm}

::: 

### Education Level x Gender

{{< include resources/balance_educ_g_sex_wday.md >}}
:Distribution Balance {#tbl-beduc_g_sexwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_educ_g_sex_wday_sm.md >}}
:Match Quality: Mean {#tbl-mneduc_g_sexwdaysm}

## Median 

{{< include resources/median_educ_g_sex_wday_sm.md >}}
:Match Quality: Median {#tbl-mdeduc_g_sexwdaysm}

## SD 

{{< include resources/sd_educ_g_sex_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdeduc_g_sexwdaysm}

::: 

### Race x Education Level

{{< include resources/balance_race_educ_g_wday.md >}}
:Distribution Balance {#tbl-brace_educ_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_race_educ_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnrace_educ_gwdaysm}

## Median 

{{< include resources/median_race_educ_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdrace_educ_gwdaysm}

## SD 

{{< include resources/sd_race_educ_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdrace_educ_gwdaysm}

::: 

### Young Children x Education Level

{{< include resources/balance_ychild_educ_g_wday.md >}}
:Distribution Balance {#tbl-bychild_educ_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_ychild_educ_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnychild_educ_gwdaysm}

## Median 

{{< include resources/median_ychild_educ_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdychild_educ_gwdaysm}

## SD 

{{< include resources/sd_ychild_educ_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdychild_educ_gwdaysm}

::: 

### Working Status x Education Level

{{< include resources/balance_works_educ_g_wday.md >}}
:Distribution Balance {#tbl-bworks_educ_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_works_educ_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnworks_educ_gwdaysm}

## Median 

{{< include resources/median_works_educ_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdworks_educ_gwdaysm}

## SD 

{{< include resources/sd_works_educ_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdworks_educ_gwdaysm}

::: 

### No of Children x Education Level

{{< include resources/balance_tchild_educ_g_wday.md >}}
:Distribution Balance {#tbl-btchild_educ_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tchild_educ_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntchild_educ_gwdaysm}

## Median 

{{< include resources/median_tchild_educ_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtchild_educ_gwdaysm}

## SD 

{{< include resources/sd_tchild_educ_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtchild_educ_gwdaysm}

::: 

### No of Adults x Education Level

{{< include resources/balance_tadult_educ_g_wday.md >}}
:Distribution Balance {#tbl-btadult_educ_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tadult_educ_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntadult_educ_gwdaysm}

## Median 

{{< include resources/median_tadult_educ_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtadult_educ_gwdaysm}

## SD 

{{< include resources/sd_tadult_educ_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtadult_educ_gwdaysm}

::: 

### Age group x Education Level

{{< include resources/balance_age_g_educ_g_wday.md >}}
:Distribution Balance {#tbl-bage_g_educ_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_age_g_educ_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnage_g_educ_gwdaysm}

## Median 

{{< include resources/median_age_g_educ_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdage_g_educ_gwdaysm}

## SD 

{{< include resources/sd_age_g_educ_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdage_g_educ_gwdaysm}

::: 

### Single/Couple x Education Level

{{< include resources/balance_cpl_educ_g_wday.md >}}
:Distribution Balance {#tbl-bcpl_educ_gwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_cpl_educ_g_wday_sm.md >}}
:Match Quality: Mean {#tbl-mncpl_educ_gwdaysm}

## Median 

{{< include resources/median_cpl_educ_g_wday_sm.md >}}
:Match Quality: Median {#tbl-mdcpl_educ_gwdaysm}

## SD 

{{< include resources/sd_cpl_educ_g_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdcpl_educ_gwdaysm}

::: 

### Education Level x Income Quantile

{{< include resources/balance_educ_g_q5_wday.md >}}
:Distribution Balance {#tbl-beduc_g_q5wdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_educ_g_q5_wday_sm.md >}}
:Match Quality: Mean {#tbl-mneduc_g_q5wdaysm}

## Median 

{{< include resources/median_educ_g_q5_wday_sm.md >}}
:Match Quality: Median {#tbl-mdeduc_g_q5wdaysm}

## SD 

{{< include resources/sd_educ_g_q5_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdeduc_g_q5wdaysm}

::: 

### Education Level x Home Ownership

{{< include resources/balance_educ_g_hhown_wday.md >}}
:Distribution Balance {#tbl-beduc_g_hhownwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_educ_g_hhown_wday_sm.md >}}
:Match Quality: Mean {#tbl-mneduc_g_hhownwdaysm}

## Median 

{{< include resources/median_educ_g_hhown_wday_sm.md >}}
:Match Quality: Median {#tbl-mdeduc_g_hhownwdaysm}

## SD 

{{< include resources/sd_educ_g_hhown_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdeduc_g_hhownwdaysm}

::: 

## Income Quantile

### Income Quantile

{{< include resources/balance_q5_wday.md >}}
:Distribution Balance {#tbl-bq5wdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_q5_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnq5wdaysm}

## Median 

{{< include resources/median_q5_wday_sm.md >}}
:Match Quality: Median {#tbl-mdq5wdaysm}

## SD 

{{< include resources/sd_q5_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdq5wdaysm}

::: 

### Income Quantile x Gender

{{< include resources/balance_q5_sex_wday.md >}}
:Distribution Balance {#tbl-bq5_sexwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_q5_sex_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnq5_sexwdaysm}

## Median 

{{< include resources/median_q5_sex_wday_sm.md >}}
:Match Quality: Median {#tbl-mdq5_sexwdaysm}

## SD 

{{< include resources/sd_q5_sex_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdq5_sexwdaysm}

::: 

### Race x Income Quantile

{{< include resources/balance_race_q5_wday.md >}}
:Distribution Balance {#tbl-brace_q5wdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_race_q5_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnrace_q5wdaysm}

## Median 

{{< include resources/median_race_q5_wday_sm.md >}}
:Match Quality: Median {#tbl-mdrace_q5wdaysm}

## SD 

{{< include resources/sd_race_q5_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdrace_q5wdaysm}

::: 

### Young Children x Income Quantile

{{< include resources/balance_ychild_q5_wday.md >}}
:Distribution Balance {#tbl-bychild_q5wdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_ychild_q5_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnychild_q5wdaysm}

## Median 

{{< include resources/median_ychild_q5_wday_sm.md >}}
:Match Quality: Median {#tbl-mdychild_q5wdaysm}

## SD 

{{< include resources/sd_ychild_q5_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdychild_q5wdaysm}

::: 

### Working Status x Income Quantile

{{< include resources/balance_works_q5_wday.md >}}
:Distribution Balance {#tbl-bworks_q5wdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_works_q5_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnworks_q5wdaysm}

## Median 

{{< include resources/median_works_q5_wday_sm.md >}}
:Match Quality: Median {#tbl-mdworks_q5wdaysm}

## SD 

{{< include resources/sd_works_q5_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdworks_q5wdaysm}

::: 

### No of Children x Income Quantile

{{< include resources/balance_tchild_q5_wday.md >}}
:Distribution Balance {#tbl-btchild_q5wdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tchild_q5_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntchild_q5wdaysm}

## Median 

{{< include resources/median_tchild_q5_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtchild_q5wdaysm}

## SD 

{{< include resources/sd_tchild_q5_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtchild_q5wdaysm}

::: 

### No of Adults x Income Quantile

{{< include resources/balance_tadult_q5_wday.md >}}
:Distribution Balance {#tbl-btadult_q5wdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tadult_q5_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntadult_q5wdaysm}

## Median 

{{< include resources/median_tadult_q5_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtadult_q5wdaysm}

## SD 

{{< include resources/sd_tadult_q5_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtadult_q5wdaysm}

::: 

### Age group x Income Quantile

{{< include resources/balance_age_g_q5_wday.md >}}
:Distribution Balance {#tbl-bage_g_q5wdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_age_g_q5_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnage_g_q5wdaysm}

## Median 

{{< include resources/median_age_g_q5_wday_sm.md >}}
:Match Quality: Median {#tbl-mdage_g_q5wdaysm}

## SD 

{{< include resources/sd_age_g_q5_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdage_g_q5wdaysm}

::: 

### Single/Couple x Income Quantile

{{< include resources/balance_cpl_q5_wday.md >}}
:Distribution Balance {#tbl-bcpl_q5wdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_cpl_q5_wday_sm.md >}}
:Match Quality: Mean {#tbl-mncpl_q5wdaysm}

## Median 

{{< include resources/median_cpl_q5_wday_sm.md >}}
:Match Quality: Median {#tbl-mdcpl_q5wdaysm}

## SD 

{{< include resources/sd_cpl_q5_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdcpl_q5wdaysm}

::: 

### Education Level x Income Quantile

{{< include resources/balance_educ_g_q5_wday.md >}}
:Distribution Balance {#tbl-beduc_g_q5wdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_educ_g_q5_wday_sm.md >}}
:Match Quality: Mean {#tbl-mneduc_g_q5wdaysm}

## Median 

{{< include resources/median_educ_g_q5_wday_sm.md >}}
:Match Quality: Median {#tbl-mdeduc_g_q5wdaysm}

## SD 

{{< include resources/sd_educ_g_q5_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdeduc_g_q5wdaysm}

::: 

### Income Quantile x Home Ownership

{{< include resources/balance_q5_hhown_wday.md >}}
:Distribution Balance {#tbl-bq5_hhownwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_q5_hhown_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnq5_hhownwdaysm}

## Median 

{{< include resources/median_q5_hhown_wday_sm.md >}}
:Match Quality: Median {#tbl-mdq5_hhownwdaysm}

## SD 

{{< include resources/sd_q5_hhown_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdq5_hhownwdaysm}

::: 

## Home Ownership

### Home Ownership

{{< include resources/balance_hhown_wday.md >}}
:Distribution Balance {#tbl-bhhownwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_hhown_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnhhownwdaysm}

## Median 

{{< include resources/median_hhown_wday_sm.md >}}
:Match Quality: Median {#tbl-mdhhownwdaysm}

## SD 

{{< include resources/sd_hhown_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdhhownwdaysm}

::: 

### Home Ownership x Gender

{{< include resources/balance_hhown_sex_wday.md >}}
:Distribution Balance {#tbl-bhhown_sexwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_hhown_sex_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnhhown_sexwdaysm}

## Median 

{{< include resources/median_hhown_sex_wday_sm.md >}}
:Match Quality: Median {#tbl-mdhhown_sexwdaysm}

## SD 

{{< include resources/sd_hhown_sex_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdhhown_sexwdaysm}

::: 

### Race x Home Ownership

{{< include resources/balance_race_hhown_wday.md >}}
:Distribution Balance {#tbl-brace_hhownwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_race_hhown_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnrace_hhownwdaysm}

## Median 

{{< include resources/median_race_hhown_wday_sm.md >}}
:Match Quality: Median {#tbl-mdrace_hhownwdaysm}

## SD 

{{< include resources/sd_race_hhown_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdrace_hhownwdaysm}

::: 

### Young Children x Home Ownership

{{< include resources/balance_ychild_hhown_wday.md >}}
:Distribution Balance {#tbl-bychild_hhownwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_ychild_hhown_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnychild_hhownwdaysm}

## Median 

{{< include resources/median_ychild_hhown_wday_sm.md >}}
:Match Quality: Median {#tbl-mdychild_hhownwdaysm}

## SD 

{{< include resources/sd_ychild_hhown_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdychild_hhownwdaysm}

::: 

### Working Status x Home Ownership

{{< include resources/balance_works_hhown_wday.md >}}
:Distribution Balance {#tbl-bworks_hhownwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_works_hhown_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnworks_hhownwdaysm}

## Median 

{{< include resources/median_works_hhown_wday_sm.md >}}
:Match Quality: Median {#tbl-mdworks_hhownwdaysm}

## SD 

{{< include resources/sd_works_hhown_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdworks_hhownwdaysm}

::: 

### No of Children x Home Ownership

{{< include resources/balance_tchild_hhown_wday.md >}}
:Distribution Balance {#tbl-btchild_hhownwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tchild_hhown_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntchild_hhownwdaysm}

## Median 

{{< include resources/median_tchild_hhown_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtchild_hhownwdaysm}

## SD 

{{< include resources/sd_tchild_hhown_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtchild_hhownwdaysm}

::: 

### No of Adults x Home Ownership

{{< include resources/balance_tadult_hhown_wday.md >}}
:Distribution Balance {#tbl-btadult_hhownwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_tadult_hhown_wday_sm.md >}}
:Match Quality: Mean {#tbl-mntadult_hhownwdaysm}

## Median 

{{< include resources/median_tadult_hhown_wday_sm.md >}}
:Match Quality: Median {#tbl-mdtadult_hhownwdaysm}

## SD 

{{< include resources/sd_tadult_hhown_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdtadult_hhownwdaysm}

::: 

### Age group x Home Ownership

{{< include resources/balance_age_g_hhown_wday.md >}}
:Distribution Balance {#tbl-bage_g_hhownwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_age_g_hhown_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnage_g_hhownwdaysm}

## Median 

{{< include resources/median_age_g_hhown_wday_sm.md >}}
:Match Quality: Median {#tbl-mdage_g_hhownwdaysm}

## SD 

{{< include resources/sd_age_g_hhown_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdage_g_hhownwdaysm}

::: 

### Single/Couple x Home Ownership

{{< include resources/balance_cpl_hhown_wday.md >}}
:Distribution Balance {#tbl-bcpl_hhownwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_cpl_hhown_wday_sm.md >}}
:Match Quality: Mean {#tbl-mncpl_hhownwdaysm}

## Median 

{{< include resources/median_cpl_hhown_wday_sm.md >}}
:Match Quality: Median {#tbl-mdcpl_hhownwdaysm}

## SD 

{{< include resources/sd_cpl_hhown_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdcpl_hhownwdaysm}

::: 

### Education Level x Home Ownership

{{< include resources/balance_educ_g_hhown_wday.md >}}
:Distribution Balance {#tbl-beduc_g_hhownwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_educ_g_hhown_wday_sm.md >}}
:Match Quality: Mean {#tbl-mneduc_g_hhownwdaysm}

## Median 

{{< include resources/median_educ_g_hhown_wday_sm.md >}}
:Match Quality: Median {#tbl-mdeduc_g_hhownwdaysm}

## SD 

{{< include resources/sd_educ_g_hhown_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdeduc_g_hhownwdaysm}

::: 

### Income Quantile x Home Ownership

{{< include resources/balance_q5_hhown_wday.md >}}
:Distribution Balance {#tbl-bq5_hhownwdaysm}

::: {.panel-tabset} 

## Mean 

{{< include resources/mean_q5_hhown_wday_sm.md >}}
:Match Quality: Mean {#tbl-mnq5_hhownwdaysm}

## Median 

{{< include resources/median_q5_hhown_wday_sm.md >}}
:Match Quality: Median {#tbl-mdq5_hhownwdaysm}

## SD 

{{< include resources/sd_q5_hhown_wday_sm.md >}}
:Match Quality: Std Dev {#tbl-sdq5_hhownwdaysm}

::: 

